config/routes.rb
Rails.application.routes.draw do
  root 'personal_banks#dashboard'
  resources :personal_banks

end

app/models/personal_bank.rb
class PersonalBank < ActiveRecord::Base
  def self.balance
    if self.all.empty?
      0.0
    else
      self.all.reduce(0.0) {|sum, x| sum + x.amount.to_f}
    end
  end
  def self.num_of_trans
    self.count
  end
  def self.monthly_expenses
    array = self.all.select {|x| (x.created_at.mon - Time.now.mon ) == 0}
    array.reduce(0.0) {|sum, x| sum + x.amount.to_f}
  end
  def self.last_months_expenses
    array = self.all.select {|x| (x.created_at.mon - Time.now.mon ) == -1}
    array.reduce(0.0) {|sum, x| sum + x.amount.to_f}
  end
  def self.last_months_num
    array = self.all.select {|x| (x.created_at.mon - Time.now.mon ) == -1}
    array.count
  end
  def self.largest_expense
    array1= []
    hash = {}
    self.all.each do |x|
      hash = {x.amount => x.exhanges}
    end
    self.all.each do |x|
      array1 << x.amount
    end
    # h.each {|key, value| puts "#{key} is #{value}" }
    hash[array1.max]
  end
  def self.largest_expense_this_month
    array = self.all.select {|x| (x.created_at.mon - Time.now.mon ) == 0}
    array1 = []
    hash = {}
    array.each do |x|
      hash = {x.amount => x.exhanges}
    end
    array.each do |x|
      array1 << x.amount
    end
    # h.each {|key, value| puts "#{key} is #{value}" }
    hash[array1.max]
  end
  def self.spent_most_money_at
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/personal_banks_controller.rb
class PersonalBanksController < ApplicationController
  before_action :set_personal_bank, only: [:show, :edit, :update, :destroy]

  def dashboard
    @personal_banks = PersonalBank.all
  end
  # GET /personal_banks
  # GET /personal_banks.json
  def index
    @personal_banks = PersonalBank.all
  end

  # GET /personal_banks/1
  # GET /personal_banks/1.json
  def show
  end

  # GET /personal_banks/new
  def new
    @personal_bank = PersonalBank.new
  end

  # GET /personal_banks/1/edit
  def edit
  end

  # POST /personal_banks
  # POST /personal_banks.json
  def create
    @personal_bank = PersonalBank.new(personal_bank_params)

    respond_to do |format|
      if @personal_bank.save
        format.html { redirect_to @personal_bank, notice: 'Personal bank was successfully created.' }
        format.json { render :show, status: :created, location: @personal_bank }
      else
        format.html { render :new }
        format.json { render json: @personal_bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personal_banks/1
  # PATCH/PUT /personal_banks/1.json
  def update
    respond_to do |format|
      if @personal_bank.update(personal_bank_params)
        format.html { redirect_to @personal_bank, notice: 'Personal bank was successfully updated.' }
        format.json { render :show, status: :ok, location: @personal_bank }
      else
        format.html { render :edit }
        format.json { render json: @personal_bank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personal_banks/1
  # DELETE /personal_banks/1.json
  def destroy
    @personal_bank.destroy
    respond_to do |format|
      format.html { redirect_to personal_banks_url, notice: 'Personal bank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal_bank
      @personal_bank = PersonalBank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personal_bank_params
      params.require(:personal_bank).permit(:amount, :exhanges, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/personal_banks_helper.rb
module PersonalBanksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wallet</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/personal_banks/_form.html.erb
<%= form_for(@personal_bank) do |f| %>
  <% if @personal_bank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@personal_bank.errors.count, "error") %> prohibited this personal_bank from being saved:</h2>

      <ul>
      <% @personal_bank.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label "From / To" %><br>
    <%= f.text_field :exhanges %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/personal_banks/dashboard.html.erb
<%= @personal_banks.balance %>
<%= @personal_banks.num_of_trans %>

<%= link_to "Transactions", personal_banks_path %>
<%= link_to "Add a new transaction", new_personal_bank_path %>

app/views/personal_banks/edit.html.erb
<h1>Editing Personal Bank</h1>

<%= render 'form' %>

<%= link_to 'Show', @personal_bank %> |
<%= link_to 'Back', personal_banks_path %>

app/views/personal_banks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Personal Banks</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Exhanges</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personal_banks.each do |personal_bank| %>
      <tr>
        <td><%= personal_bank.amount %></td>
        <td><%= personal_bank.exhanges %></td>
        <td><%= personal_bank.description %></td>
        <td><%= link_to 'Show', personal_bank %></td>
        <td><%= link_to 'Edit', edit_personal_bank_path(personal_bank) %></td>
        <td><%= link_to 'Destroy', personal_bank, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personal bank', new_personal_bank_path %>

app/views/personal_banks/new.html.erb
<h1>New Personal Bank</h1>

<%= render 'form' %>

<%= link_to 'Back', personal_banks_path %>

app/views/personal_banks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @personal_bank.amount %>
</p>

<p>
  <strong>Exhanges:</strong>
  <%= @personal_bank.exhanges %>
</p>

<p>
  <strong>Description:</strong>
  <%= @personal_bank.description %>
</p>

<%= link_to 'Edit', edit_personal_bank_path(@personal_bank) %> |
<%= link_to 'Back', personal_banks_path %>